# Generated by Django 2.0.5 on 2018-05-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_type', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(verbose_name='date_time')),
            ],
        ),
    ]
