# Generated by Django 2.0.5 on 2018-05-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='date_time',
        ),
    ]
